site_name: Neural Pipeline Search
docs_dir: docs
repo_url: https://github.com/automl/neps
repo_name: automl/neps
edit_uri: ""

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - admonition
  - attr_list
  - md_in_html

extra:
  version:
    provider: mike

nav:
  - Introduction and Installation: 'README.md'
  - Getting Started: 'getting_started.md'
  - The run_pipeline Function: 'run_pipeline.md'
  - The pipeline_space: 'pipeline_space.md'
  - The neps.run Function: 'neps_run.md'
  - Analysing Runs: 'analyse.md'
  - Parallelization: 'parallelization.md'
  - Alternatives: 'alternatives.md'
  - Citations: 'citations.md'
  - Contributing:
      - Introduction: "contributing/README.md"
      - Installation for Contributors: "contributing/installation.md"
      - Checks and Tests: "contributing/tests.md"
      - Managing Dependencies: "contributing/dependencies.md"
      - Releasing a New Version: "contributing/releasing.md"
      - Documentation: "contributing/documentation.md"
      - Roadmap: "contributing/roadmap.md"
